- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Import Bastion setup variables
      include_vars: vars/bastion_setup 
    
    - name: Import VPC setup Variables
      include_vars: vars/output_var